### ISSUE TITLE
Color in treeview display for custom type

### ISSUE THREAD

**Issue by ChrisRackauckas** [JunoLab/Juno.jl#150]
![capture](https://user-images.githubusercontent.com/1814174/43037604-c5f89ee0-8cc3-11e8-8be9-8b8c8d0b2d0a.PNG)

How do I get pretty colors in my show output for the header?

**Comment by pfitzseb** [comment]
There are two solutions to that problem:

#### Plain text output
You can use ANSI color codes which will work in the REPL and in Juno:
```julia
macro CSI_str(str)
    return :(string("\x1b[", $(esc(str)), "m"))
end

import TreeViews: hastreeview, numberofnodes, treelabel, treenode
struct Foo
    field1
    field2
end

struct Bar
    a
    field1
end

hastreeview(::Foo) = true
hastreeview(::Bar) = true

numberofnodes(::Foo) = 1
# colors can be specified with SGR (see https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters)
treelabel(io::IO, x::Foo, i::Int, ::MIME"text/plain") = 
  print(io, "and ", CSI"31", "this", CSI"0", " is my first field ")
treelabel(io::IO, x::Foo, ::MIME"text/plain") = 
  print(io, "I'm a ", CSI"38;2;200;0;200", "Foo", CSI"0")

Foo(Bar(1,2), 3)
```
![image](https://user-images.githubusercontent.com/6735977/43045422-dced4ef2-8db8-11e8-9879-1bcf9b1e1e67.png)

This doesn't completely work with the released versions of julia-client and ink, but I'll push a fix momentarily.

#### HTML
```julia
treelabel(io::IO, x::Foo, ::MIME"text/html") = 
  print(io, "<span>I'm a <span style=\"color:blue\">HTMLified</span> Foo</span>")
```
![image](https://user-images.githubusercontent.com/6735977/43045476-88389d8e-8db9-11e8-851b-f4d01c5d549d.png)

------
The second option obviously allows for more customization since you can do basically everything there, while the first one is more likely to be supported everywhere.

It might be worthwhile to also add support for a `appliaction/juno+inline` mime type since you might want to reuse Atom's styling. Could also pass an `IOContext` with a `juno_colors` key as it happens with the plot pane.

**Comment by ChrisRackauckas** [comment]
>It might be worthwhile to also add support for a appliaction/juno+inline mime type since you might want to reuse Atom's styling. Could also pass an IOContext with a juno_colors key as it happens with the plot pane.

That would be cool! I don't know the colors well so I just kinda picked one... and it looks... okay? Having easy cohesion would be nice.

**Comment by ChrisRackauckas** [comment]
>It might be worthwhile to also add support for a appliaction/juno+inline mime type since you might want to reuse Atom's styling. Could also pass an IOContext with a juno_colors key as it happens with the plot pane.

That would be cool! I don't know the colors well so I just kinda picked one... and it looks... okay? Having easy cohesion would be nice.

**Comment by ChrisRackauckas** [comment]
It doesn't seem to nest well:

![capture](https://user-images.githubusercontent.com/1814174/43159873-733e8a9e-8f38-11e8-96cc-8158c5e140ba.PNG)

**Comment by pfitzseb** [comment]
That's implemented in the last version of Atom.jl (see [here](http://docs.junolab.org/latest/man/info_developer.html)).

**Comment by pfitzseb** [comment]
And if you want the type color used in the editor you can use 
`treelabel(..., ::MIME"application/juno+inline") = print(io, "<span class=\"syntax--support syntax--type syntax--julia\">I look like a type</span>")`
