### ISSUE TITLE
New Standard Keyboard Shortcut: Interrupt Julia

### ISSUE THREAD

**Issue by ChrisRackauckas** [JunoLab/Juno.jl#16]
I think `Ctrl+j` `Ctrl+i` should be introduced as a standard keyboard command to interrupt Julia. It's a much less nuclear option than killing the Julia process and most IDEs have something for it.

**Comment by MikeInnes** [comment]
We already have a couple of shortcuts – I think it's `Ctrl-C` on macs and `Ctrl-Shift-C` on Windows.

One reason I'm reluctant to give more support to interrupts is that (1) they are not well supported on all platforms and (2) even when they are supported, they play poorly with any kind of concurrency since you don't know what you're interrupting (and stuff that isn't interrupted can carry on).

To solve those issues I think we need to implement a real API for doing this stuff.

**Comment by ChrisRackauckas** [comment]
Okay, then I'll leave interrupts out of the docs for now since it sounds like that causes more issues than needed right now.

**Comment by pfitzseb** [comment]
https://github.com/JunoLab/atom-julia-client/pull/404
