### ISSUE TITLE
world age increments on every entry in the embedded REPL

### ISSUE THREAD

**Issue by TsurHerman** [JunoLab/Juno.jl#167]
<img width="411" alt="juno_world counter" src="https://user-images.githubusercontent.com/3405405/44872440-38a5cb80-ac9e-11e8-95e9-0dc7f8397cb3.png">

this does not happen on a 
<img width="404" alt="repl_world_age" src="https://user-images.githubusercontent.com/3405405/44872628-ba95f480-ac9e-11e8-96c3-8ce0d006037b.png">
terminal REPL

**Comment by pfitzseb** [comment]
Great observation, thanks for reporting this!

While the world counter increase isn't very problematic on it's own it indicates recompilation, which made the REPL inside of Juno (much) slower than necessary.

Fixed with https://github.com/JunoLab/Atom.jl/commit/ba5511d2a2a2ebaf76267cfbbb66d569d09e9eb4.

**Comment by TsurHerman** [comment]
Exactly
