### ISSUE TITLE
Autocompletion doesn't work while worker 1 is busy.

### ISSUE THREAD

**Issue by xanfus** [JunoLab/Juno.jl#182]
## Details
- Atom version: 1.31.2
- Julia version: 0.7.0 
- OS: Ubuntu MATE 16.04.5 LTS
- Package versions:
  - Atom.jl: 0.7.8
  - julia-client: 0.7.8 
  - ink: 0.9.11

Popup with guesses doesn't appear.
### Steps to reproduce
1. Make worker 1 busy for a while.
2. While worker 1 is busy,
2.1. edit any (.jl?) file by dialing "\chi". Observe no popup right to the line dealt. Attempt to complete will result in tabulation.
3. While worker 1 is busy,
3.1 run Julia terminal from Atom's Julia menu.
3.2 edit prompt by dialing "\chi". Completion executes as designed.

**Comment by SamDM** [comment]
I am having same issue now since the last update. Autocompletion in the editor only works when Julia is not running. It does keep working in the REPL. As soon as I kill Julia, autocompletion in the editor works again.
* Atom version: 1.32.2
* Julia version: 1.0.2
* OS: Manjaro linux
* Package versions:
atom-material-syntax@1.0.8
atom-material-syntax-dark@1.0.0
atom-material-ui@2.1.3
bracket-colorizer@1.2.0
file-icons@2.1.26
indent-detective@0.3.1
ink@0.9.13
julia-client@0.7.11
language-julia@0.18.0
latex-completions@0.3.6
platformio-ide-terminal@2.8.4
tool-bar@1.1.11
uber-juno@0.2.0
vim-mode-plus@1.36.0

I have tried reinstalling as recommended in the Juno FAQ.

**Comment by SamDM** [comment]
Hmm, maybe I misunderstood the issue. Since the latest update autocomplete stops working while the Julia REPL is active. It doesn't matter wether or not a loop is running. The problem remains even when the REPL is idle and waiting for input. When I stop the REPL (CTRL-J, CTRL-K) then autocompletion comes back to life.

**Comment by SamDM** [comment]
Ok, looking into it further, it seems like when Julia is running, some (but not all) autocompletion entries do show up in the autocompletion menu, but they fail to bubble up to the top of the menu when refining your search.

E.g. when I type `Base.` then I can see macros, types, packages and constants in the autocomplete menu (but no functions). However, partly typing one of the suggested names does not make it move to the top suggestions. Also pressing tab results in inserting a tab instead of completing the top suggestion (which is always the same: `Base.@MIME_str` since top suggestions don't change by typing more characters). The same happens with LaTeX completions: typing `\in<TAB>` does not result in the `∈` symbol, it just puts a tab character, resulting in the literal text `\in` followed by a tab. Also completion of previously entries words does not work when Julia REPL is open. E.g. if have the word `foobar` somewhere in my file, then typing `fooba` somewhere else does not result in showing `foobar` in the autocomplete menu.

When I kill Julia (CTRL-J, CTRL-K) then LaTeX completions and word completions work again.
Previous to the last update, everything worked.

I'd like to help debug this, but I have no clue about how the internals of atom and the julia-client work. But any pointers to where I can start looking are welcome :)

**Comment by SamDM** [comment]
Hi, thx for helping me debug this.

Before I try you suggestion I would like to report on something else I've tried and didn't work. I backed up my atom folder `mv ~/.atom ~/.atom.back` and restarted atom, then re-installed the uber-juno package in fresh atom environment. So the only packages installed were the uber-juno dependencies. All other atom settings are defaults. However, the autocompletion issue is exactly the same a before.

**Comment by SamDM** [comment]
Ok, I removed both `~/.atom` and `~/.julia` en re-installed everything.

In contrast to previous attempts, this also triggered julia packages related to Juno to re-compile.

Now things work again :)

**Comment by xanfus** [comment]
> Depends on what you mean by busy -- if you're running a loop without any yields then yes, Julia won't be able to give you autocompletions. If, on the other hand, you are `yield`ing in your loop...

Yes, i did mute loop.

**Comment by pfitzseb** [comment]
Alright, then barring a rework of how we handle user executed code (namely in a different process) this won't change in the future. I could try looking into caching autocompletions again, but that's pretty difficult considering how context sensitive they are now.
