### ISSUE TITLE
Persistent Julia kernels

### ISSUE THREAD

**Issue by staticfloat** [JunoLab/Juno.jl#208]
I would love it if I can start a long-running computation, shut my laptop, then later open it again, reconnect to the remote kernel and view the results.  Is there any way to use e.g. `tmux` with a stream buffering program to get this functionality?

**Comment by ChrisRackauckas** [comment]
Automatically inserting `tmux` or `screen`  calls so that way it makes a persistent session and keeps grabbing the same one? I'd enjoy that. That is generally how I use Julia when sshing.

**Comment by staticfloat** [comment]
I assume that would work, but I don't know how the communication works, which is a problem; ideally you would have a way to "replay output since the last time I connected", or something like that.

**Comment by pfitzseb** [comment]
Wait, you can already have a persistent `tmux` session:
![tmux](https://user-images.githubusercontent.com/6735977/50052410-eb9e1600-0123-11e9-86fa-bd049f103a39.png)

Ouput/`display` buffering would be cool though, I agree. Although generating output is much faster than the actual computation in most cases, so dunno how necessary that is.

**Comment by staticfloat** [comment]
What does `Juno.connect(8887)` do?  Do I need to do that manually?

**Comment by pfitzseb** [comment]
It connects to port 8887 :)
You shouldn't need to do anything manually if you check the `Use a persistent tmux session` in the julia-client settings (see screenshot). Juno will ssh to the server and try to start a tmux session named `juno_tmux_session` (or whatever you put in that setting); if a session of that name already exists we attach to it and `send-keys` the `Juno.connect(port)` command.
Note that you need tmux v2.x for that because I use `{{left}}` to identify the tmux pane and couldn't be bothered to find out how to do something like that with tmux 1.x.


Otherwise you could also start a remote tmux session manually with proper ssh port forwarding and connect yourself (see [here](http://docs.junolab.org/release-0.7/man/faq.html#Connecting-to-a-Julia-session-on-a-remote-machine-1)).
