### ISSUE TITLE
Split additional argument by whitespace when invoking Julia

### ISSUE THREAD

**Issue by mortenpi** [JunoLab/Juno.jl#243]
Currently it seems that the string in "Additional Julia Startup Arguments" gets passed as a single argument to `julia` (`foo bar` get passed as `julia "foo bar"`). The only thing that seems to happen to the argument is that the whitespace around the commas gets trimmed (`foo, bar` gets passed as julia "foo,bar").

I propose that the argument be split at whitespace and passed as separate arguments, like in the terminal. So `foo bar` gets passed as `julia "foo" "bar"`. This makes it possible to actually pass multiple additional arguments, which is not possible at the moment.

A small annoyance is dealing with quotes in the arguments. Naively splitting would pass `foo "bar baz"` as `julia foo '"bar' 'baz"'`, whereas you'd probably want `julia foo "bar baz"`.

**Comment by pfitzseb** [comment]
I've improved the description for that setting in https://github.com/JunoLab/atom-julia-client/commit/f9d16cf1aa89eabe16504bb706ff2439dd134a54.

Juno expects a comma-separated list of arguments here, and it should never be necessary to quote anything (unless you actually want the quotes in your argument). Unfortunately there's also a bug in the current release that means you can't actually pass more than one argument (also fixed by the commit above).

**Comment by mortenpi** [comment]
Lovely, tested master and passing multiple comma-separated arguments works now! Thanks!

Still, I feel that interpreting that option like it would be on the command line would be more intuitive and simpler for the user (case in point, #244). Are you strongly against that or is it more of a matter of how to allocate dev time? I do see how it is a bit of work to get it right, and it's not very important, but maybe worth leaving open as a "good first issue"?
