### ISSUE TITLE
[FR] Debugger - working with local state

### ISSUE THREAD

**Issue by BioTurboNick** [JunoLab/Juno.jl#274]
It would be useful to be able to modify the local state at a breakpoint, or to exit the debugger with a copy of the local state preserved. This would allow a troublesome next step to be played with, without taking time to set the environment up again.

**Comment by pfitzseb** [comment]
You can execute arbitrary code at the `debug>` prompt in the REPL. Do you want something else, and if so, what?

**Comment by BioTurboNick** [comment]
I want to be able to create new variables (either in local context or preserved after debugging), and be able to use the command buffer (up/down arrow at prompt).

-- Just noticed that `global x = 5` does allow me to create a new variable `x`, while `x = 5` alone is evaluated but no variable is created. However, the global variable does not appear in Workspace and is not preserved when debugging is exited.

Some of this is motivated by debugging code that's a bit tricky, like stepping into a broadcasted function. It would be easier to try debugging a single instance of the function using just one of the set of arguments generated by the prior steps. (Unless I've missed something about this, which is quite likely.) So I'd like to save the state, drop out of debugging, and then start debugging again from that point, unless there's another way.

**Comment by pfitzseb** [comment]
https://github.com/JunoLab/Atom.jl/commit/54881d25c7f74fdfd7825eab443737db298b4139 implements a REPL histroy provider.

You can as a matter of fact create global variables, but it's slightly tricky -- `global x = 5` will create a new global in whatever module you've stepped into (e.g. `Base`), so that's where you need to look for them. You can also do something like `eval(Main, :(x=$(sin(5))))` to put a new variable into `Main`, but that's pretty ugly.

**Comment by BioTurboNick** [comment]
Closing because Juno is no longer getting updates.
