### ISSUE TITLE
Juno terminal and interaction with the editor

### ISSUE THREAD

**Issue by ViralBShah** [JunoLab/Juno.jl#28]
I prefer to use the regular julia terminal much more than the Juno one. Can we embed some js terminal into Juno, so that the regular julia terminal can just work in it? 

The other thing I don't like is that when you do inline evaluation, all that code is evaluated, but not visible in the terminal. Thus, visible state is split across the editor and the terminal. The workflow I like is to send code from the editor into the terminal, and have it execute as if it had been typed in there. That way, all my visible state is in the terminal window.

**Comment by MikeInnes** [comment]
Terminal integration is clearly a great feature to have for many reasons. The REPL is currently much more polished and familiar for many people than the console implementation, but even aside from that it's useful to have it for developing software designed to work in a terminal, or for using tools like `htop`.

From what I can tell the most promising route is [term3](https://github.com/Floobits/atom-term3), which has a service API – so we may be able to use that fairly directly. (Or we can fork it with a small patch and register term4 :) Obviously if anyone has tried different JS terminals and has something they really like then suggestions are welcome.

RE inline results, once we have terminal integration it makes total sense to provide this as an option. I think there's an interesting meta-issue here though, which is: How do we encourage people to use Juno's tools effectively, rather than simply as a more (or less) convenient version of their current workflow? For example, inline eval opens up a really great workflow where you can tweak a package or script as you're working on it and then carry on using it from the terminal. No more state is shared than if you restarted the repl and re-ran `using Foo`, it's just a hell of a lot faster. I think nudging people towards that kind of things would be great but how is an open problem.

**Comment by ViralBShah** [comment]
I think we should certainly nudge people to try new workflows. However, the process should try to upgrade them from how they like to do things. 

There are cases where I like inline evaluation and cases where I don't. There is definitely the right balance somewhere.

**Comment by ViralBShah** [comment]
For now, how about ctrl-enter send it to the terminal repl (echo it in there), and shift-enter be inline?

**Comment by pfitzseb** [comment]
With [this](https://github.com/JunoLab/atom-julia-client/pull/332) PR there's the option to display results in the Juno console instead of inline on `Ctrl-Enter`. That good enough, or do you really want them to be displayed in the external REPL?

**Comment by tbole** [comment]
It would be extremely helpful, if it was possible to simply use an external terminal. I think most standalone terminals are much superior to the one integrated in Atom.
Since this issue is rather old, is this feature possibly already available?

**Comment by pfitzseb** [comment]
Sure, there's a "Connect Terminal" command that does precisely that. Unfortunately it's broken at the moment (fixed with https://github.com/JunoLab/atom-julia-client/commit/e78ab1b0a1e694eb274b34a9bf2943774fd42b1b), but you can just use the "Connect External Process" command until a new version with the fix is out.

**Comment by tbole** [comment]
Great! Didn't notice that option, since it's only available from the palette, but not from the menu. Waiting for the next release!
