### ISSUE TITLE
[FR] Add `@debug` alias for `@enter`

### ISSUE THREAD

**Issue by dpsanders** [JunoLab/Juno.jl#451]
I can never remember `@enter`. It seems like `Juno.@debug` would be more natural.

**Comment by aviatesk** [comment]
`@enter` still makes sense since currently JuliaInterpreter-based debugging is only possible via "entering" into a function call.
It's also consistent with other debugger frontends like [Debugger.jl](https://github.com/JuliaDebug/Debugger.jl/blob/master/README.md)

otoh, the cost of using the name `@debug` would be very small as far as it's not exported though. 
In the future, when JuliaInterpreter begins to allow debugging toplevel scripts, we may want to name it "debug", but then it doesn't need to be macro anymore.

Thoughts ?
/cc @pfitzseb @timholy @KristofferC

**Comment by KristofferC** [comment]
`@debug` is the command to log with the debug log level. Could arguably be a bit confusing to use the same macro name?

**Comment by pfitzseb** [comment]
Yeah, the name collision with the logging macros is unfortunate. How about `@step` (`@stepinto`?), maybe?

**Comment by phlavenk** [comment]
I don't think we need a macro for this once Juno supports something like `ctrl-shift-F5` to start debugging the active line under cursor.
