### ISSUE TITLE
better integration with Base.show system

### ISSUE THREAD

**Issue by stevengj** [JunoLab/Juno.jl#91]
I haven't really used Juno, so I'm sorry if I'm a latecomer here.

However, I have to say I'm a bit disappointed that Juno chose to roll its own completely separate multimedia display system rather than building on top of the existing one in Base.

For example, if I've defined a `show(io, ::MIME"text/markdown", x)` method for my type, why should I also have to define a `render` method to get markdown display in Juno?  Similarly for `show(io, ::MIME"image/png", x)` etcetera?

I get that Juno has additional display formats, like tree views.  But couldn't that have been done just by defining an `application/juno` MIME type with an appropriate serialization format (e.g. JSON, since you use that anyway elsewhere and it is easy for packages to write even without using JSON.jl)?

If there is something that really can't be done with the Base display system for Juno, it surely would have been better to improve Base as needed than to roll a completely independent display system just for Juno.

cc @StefanKarpinski

**Comment by ChrisRackauckas** [comment]
This topic has come up lately because Juno is switching to an embedded REPL instead of its current console. The issue there is that now that means that all of the fancy Juno displays no longer work when code is ran in the embedded REPL. For DiffEq this is quite tragic because the tree-views are almost necessary for appropriately looking deep into arrays of arrays. Here's a visual of master:

![capture](https://user-images.githubusercontent.com/1814174/34730068-3b1ba5c6-f513-11e7-845b-bee3571c8a91.PNG)

Not only is it unfortunate that there's now two display systems, but DiffEq's REPL display is quite bad because we've been relying on Juno's tools. IMO what needs to be happen is that the display system in Base needs to have better support for how Juno does nestings. It's bad enough that I am planning on doing the DiffEq tutorial using Juno (with Jupyter notebooks on the side for consistency) mostly because the Juno tree-view display is so important for easily introspecting values for us. Not that I have a solution for how to do those tree-views in the REPL though haha.

**Comment by stevengj** [comment]
It is trivial to define a serialization format for tree views, including tree views where the nodes themselves are arbitrary MIME data.

Creating a renderer for tree views is more difficult, but that is a separate issue entirely.

**Comment by stevengj** [comment]
More specifically, suppose we defined an `application/treeview+json` JSON-encoded serialization format for tree views.  Then:

* Any package that wanted to use this format would define a `show(io, ::MIME"application/treeview+json", x)` method for their types.

* The Juno REPL would push a `JunoDisplay` onto the display stack, with a `display(::JunoDisplay, x)` method that uses `application/treeview+json` if `x` supports it (if `mimewritable` returns `true`), otherwise it goes through a list of `text/markdown`, `image/png`, and other supported types and displays whichever one it thinks is best.

* Other front-ends that have a treeview widget could eventually also implement `application/treeview+json` support.

**Comment by MikeInnes** [comment]
Forcing renderers to work with byte strings, rather than structured data, isn't great for our purposes. We use lazy display in places (we can display circular data structures for example) for which you need to deal with anonymous functions. If the display system works with structured data this is easy for the API user and the Juno can handle the messy serialisation.

It seems like a generally good idea not to conflate API and serialisation format, because I really just want to say "this type displays as a table" and have the frontend do the right thing. Tree and table views could happily be displayed in the REPL, but you'd serialise them to text rather than JSON – that's just an implementation detail.

There are other issues which the Base system doesn't have an answer to, including that we have multiple possible displays in Juno (editor, repl, plot pane etc). The display stack doesn't work for this; you *can* display markdown in the plot pane but you usually don't want to. And it gets even worse when you have multiple *inputs*, and the choice of display depends on the input used.

In general I've found the base display system to be *very* heavily specialised to repl and notebook-like interfaces (strangely enough). Understandable, but for our purposes it was an uphill battle to work with, and I think it's been much more straightforward to build something more powerful while being reasonably backwards-compatible (and we could easily improve on that; supporting `show(io, ::MIME"text/markdown", x)` is easy to do for example).

**Comment by stevengj** [comment]
"Structured data" is just a set of bytes with a particular interpretation; it's not mutually exclusive with serialization.  I mentioned JSON because that is precisely a serialization format for representing structured data.

I'm don't understand why you think there is an issue with multiple displays.   The `display(::JunoDisplay, x)` function can display `x` in any and all formats that it wants.  It can put an image in the plot pane and markdown in the editor (assuming `x` supports both), or whatever.   And if you want the choice of display to depend on the input, then just use some state to indicate which input is the source of the `display` call.

**Comment by MikeInnes** [comment]
Ok, well that sounds pretty much like what we are already doing then.

**Comment by stevengj** [comment]
Then why not do it with the Base system rather than forcing packages to use a Juno-specific system?

**Comment by MikeInnes** [comment]
As in, the specific issue of allowing packages to overload `show` to provide a tree or other Juno view?

I'm happy to see a prototype for it, but for the reasons I mentioned above I don't think it will work well. I don't deny that it _can_ be done, just like any program can be written in brainfuck, it's just unnecessary and more complex to work with stringly-typed bytes rather than normal Julia data structures.

We could support it easily enough in some special cases (e.g. non-lazy views), but that would have to be in addition to what we already have.

**Comment by stevengj** [comment]
How about you do something like this:
```jl
# TreeView.jl is a Juno-independent package that defines an API that
# types can use to define a tree view via lazy queries.
using TreeView

function Base.display(d::JunoDisplay, x)
    if hastreeview(x)
        ... use TreeView API to render tree view lazily ...
    elseif mimewritable("text/markdown", x)
        ... render markdown version using show(io, "text/markdown", x) ...
    elseif ... other supported MIME types, e.g. image/png ...
    else
        ... use show(io, "text/plain", x) fallback ...
    end
end
```
(Modify as needed to display multiple formats simultaneously, utilize state that tells Juno where the input is coming from, etcetera.)

* Packages could use TreeView (without depending on Juno) to override `TreeView.hastreeview(::MyType) = true` and then define an appropriate API that you can query to fetch different levels of the tree interactively.

* `show` methods for supported MIME types will work too.

* Other display mechanisms could implement support for tree views (e.g. Jupyter could do it via a tree-view widget, since their widgets operate by a callback mechanism that can work with lazy views).

* For displaying the nodes in the tree view themselves, Juno (and other displays) could use the same mechanism to decide how to display the nodes (i.e. is the node itself a tree view, or does it display as markdown, or is it an image, etcetera).   That way, the rich display is automatically recursive without any addition requirements on packages (i.e. a type only has to implement one level of tree view that returns the objects/labels at that level).

**Comment by MikeInnes** [comment]
Well again, this is essentially what we are doing at the moment (with a slight generalisation to views other than trees), even if we're currently missing the branch for markdown.

It would indeed be nice to factor out structured views into its own package so that it can easily be used everywhere. The only reason we've currently bundled that stuff into Juno.jl is that there's been no forcing function for a new package as yet.

**Comment by stevengj** [comment]
There's a bit of a contradiction between saying that the Base display system is an "uphill battle to work with" that is "very heavily specialised to repl and notebook-like interfaces" and at the same time say that a change to use `Base.display` is "essentially [the same as] what we are doing at the moment".   Either the whole `Base.display` design is unworkable or it requires only a slight refactoring to work with, no?

Anyway, I'm glad you now seem to agree that it would be a straightforward change.   I think it would be a big improvement for users for Juno to automatically use their existing `show` methods (not just for text/markdown, but also for things like image display)

**Comment by stevengj** [comment]
(The design in Base separates `show` from `display` precisely to allow this kind of flexibility.  e.g. IJulia sends multiple MIME types to Jupyter simultaneously.)

**Comment by MikeInnes** [comment]
Base's display system provides both a display dispatch system and a stream-based rendering system, neither of which work well for Juno, so we've had to hook in and extend it in the ways you've suggested. Whether you call that a completely new system or an integration is up to you, but that's what I thought the issue was about.

If it's just about adding support for the markdown show method, that's trivial (like I said in my first comment). We already do it with `text/plain`.

**Comment by stevengj** [comment]
What this issue is about is not forcing packages to rely on Juno and call/extend `Juno.render`.   Users who are happy with the existing `show` MIME types should be able to continue to use them (not just for markdown … there are lots of other MIME types for rich display that it seems like you could support).  Users who want a new rich-display format (e.g. tree views) should be able to do so that is independent of Juno's rendering system.  I initially thought a new MIME type would be sufficient, but a separate TreeViews (or whatever) API is fine too.

**Comment by stevengj** [comment]
As another example, if someone wanted to implement a TerminalTreeViews.jl package that works in the terminal via @Keno's [TerminalUI](https://github.com/Keno/TerminalUI.jl) package, they could do so: just push a `REPLTreeViewDisplay` onto the display stack that only handles `hastreeview(x) == true` objects and punts everything else down to the next display in the stack.

**Comment by pfitzseb** [comment]
I do intend to look into this as soon as I'm done with more pressing matters (namely the console work and performance improvements).

**Comment by jpsamaroo** [comment]
As someone who is not a user of Juno, but is trying to write a currently-unpublished UI framework package which supports multiple render outputs of various types, I'd like to know how one might manage to use Base show/display to easily render data of type X to render window Y with rendering mode/config Z.

The display stack concept seems to me to be too simplistic to handle a use case like that, since it just "blindly" picks the first display that matches the input, which is only useful for limited cases. Please correct me if I'm wrong about this!

Also, I'm not terribly up-to-date on the MIME system, but `Base.show(io, mime, x)` seems to mostly handle the above case of specifying X, Y, and Z (x == X, mime == Z, io == Y), except in the case where Z can have multiple, arbitrary degrees of freedom (like textcolor, strokecolor, font, size, etc.). Does that seem like an accurate downside to `Base.show`? If so, then I can see how that would be a show-stopper for Juno, because that is also a show-stopper for my own UI package.

**Comment by stevengj** [comment]
@jpsamaroo please don't raise unrelated discussions of the whole Base display system on this thread.  (Short answer: if you want the user to specify a particular output display `Y`, they can pass that as the first argument of `display`.   If you want to pass additional meta-information to `show`, you do so using an IOContext.)

**Comment by jpsamaroo** [comment]
Apologies if I sounded like I was trying to make a feature request for Base in this thread. I was only trying to bring some more context to the ongoing discussion by highlighting an example, but clearly I misunderstood the point of the discussion.

**Comment by davidanthoff** [comment]
Maybe a good first step would be to tackle say images/plots first and then go from there? We just use the base display system in VS Code for our plotting pane, and essentially it worked from day one with pretty much every plotting package. It would be kind of nice of all the plotting packages just had to support the base display system to get the best support in all the various editors/display systems.
